
/// ARTICLES ///
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ADMIN_ARTICLES = 'GET_ADMIN_ARTICLES';
export const UPDATE_ARTICLE_STATUS = 'UPDATE_ARTICLE_STATUS';
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE';



/// NOTIFICATIONS ///
export const ERROR_GLOBAL = 'ERROR_GLOBAL';
export const SUCCESS_GLOBAL = 'SUCCESS_GLOBAL'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';


/// USERS ///
export const AUTH_USER = 'AUTH_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const CHANGE_USER_EMAIL = 'CHANGE_USER_EMAIL';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';


/// SITE ///
export const SITE_LAYOUT = 'SITE_LAYOUT';